[[heading]]
level = 1
font.name = "Helvetica-Bold"
font.size = 18.0
font.color = 0x000000
font.superscript = false
font.italic = false
font.serif = false
font.monospace = false
font.bold = true
bbox.left = 31.184999465942383
bbox.top = 26.945993423461914
bbox.bottom = 51.73199462890625